// @generated by CSTX transport codegen — DO NOT EDIT MANUALLY

export interface CSTXNode {
  id: string;
  type: string;
  value: string;
  model: Record<string, unknown>;
  sources: string[];
  extras: Record<string, unknown>;
}

export interface CSTXEdge {
  id: string;
  source_id: string;
  target_id: string;
  relation_type: string;
  sources: string[];
  attrs: Record<string, unknown>;
}

export interface CSTXSnapshot {
  nodes: CSTXNode[];
  edges: CSTXEdge[];
  types: Record<string, unknown>;
}

export interface CSTXDelta {
  added_nodes: number;
  updated_nodes: number;
  removed_nodes: number;
  reactivated_nodes: number;
  added_edges: number;
  updated_edges: number;
  removed_edges: number;
  reactivated_edges: number;
}

export interface CSTXStat {
  nodes: number;
  edges: number;
  node_types: number;
  relation_types: number;
  node_type_counts: Record<string, number>;
  rel_type_counts: Record<string, number>;
  source_counts: Record<string, number>;
  anchor_counts: Record<string, number>;
  delta: CSTXDelta | null;
}
