/**
 * Icons a runtime config may name.
 *
 * A stat card's `icon` and a table action's `icon` arrive as strings from the
 * manifest-driven config, so neither can be a static import at the call site.
 * Resolving them through `import * as icons from 'lucide-react'` accepted every
 * name the library exports, but it also pulled all ~1500 icons and their paths
 * into the bundle — a 860 kB chunk for the handful of names a config ever uses.
 * Enumerating the supported names costs only what the list imports; an unknown
 * name resolves to nothing, which is what an unrecognised name did before.
 *
 * Adding an icon here is the way to make it usable from a config.
 */
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  BarChart3,
  Bot,
  Box,
  Bug,
  Check,
  CheckCircle2,
  ChevronRight,
  Clock,
  Cloud,
  Cpu,
  Crosshair,
  Database,
  Eye,
  EyeOff,
  FileCode,
  FileText,
  Filter,
  Fingerprint,
  Flag,
  FolderTree,
  Gauge,
  GitBranch,
  Globe,
  HardDrive,
  Hash,
  History,
  Info,
  KeyRound,
  Layers,
  Link,
  Loader2,
  Lock,
  MapPin,
  MessageSquare,
  Network,
  Package,
  Radar,
  RefreshCw,
  Route,
  Search,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  Target,
  Terminal,
  TrendingDown,
  TrendingUp,
  User,
  Users,
  Wifi,
  X,
  XCircle,
  Zap,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const LUCIDE_ICONS: Record<string, LucideIcon> = {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  BarChart3,
  Bot,
  Box,
  Bug,
  Check,
  CheckCircle2,
  ChevronRight,
  Clock,
  Cloud,
  Cpu,
  Crosshair,
  Database,
  Eye,
  EyeOff,
  FileCode,
  FileText,
  Filter,
  Fingerprint,
  Flag,
  FolderTree,
  Gauge,
  GitBranch,
  Globe,
  HardDrive,
  Hash,
  History,
  Info,
  KeyRound,
  Layers,
  Link,
  Loader2,
  Lock,
  MapPin,
  MessageSquare,
  Network,
  Package,
  Radar,
  RefreshCw,
  Route,
  Search,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  Target,
  Terminal,
  TrendingDown,
  TrendingUp,
  User,
  Users,
  Wifi,
  X,
  XCircle,
  Zap,
};

export function resolveLucideIcon(name: string | null | undefined): LucideIcon | null {
  if (!name) return null;
  return LUCIDE_ICONS[name] ?? null;
}
