import type { ComponentManifest } from '../../types/manifest';

export const cstxTableManifest: ComponentManifest = {
  type: 'cstx-table',
  displayName: 'CSTX Table',
  description:
    'Tabular display of CSTX entities with sorting, pagination, search, type filtering, and pluggable cell renderers. Columns auto-detected from data when not specified.',
  span: { minCols: 2, maxCols: 4, defaultCols: 4, growable: true },
  dataSlots: [
    {
      key: 'rows',
      label: 'Table rows',
      shape: 'array',
      required: true,
      typeHint: 'Record<string, unknown>[]',
      example: [{ id: '1', name: 'example.com', type: 'domain' }],
    },
    {
      key: 'total',
      label: 'Total row count',
      shape: 'scalar',
      required: false,
      description: 'Total number of rows on the server. Required for server-side pagination.',
    },
  ],
  propSlots: [
    {
      key: 'columns',
      label: 'Column definitions',
      type: 'object',
      description:
        'Array of { key, title, sortable?, width?, render?, renderOptions?, filterable?, align?, hidden? }. If omitted, columns are auto-inferred from data.',
    },
    {
      key: 'columnsExclude',
      label: 'Columns to exclude',
      type: 'object',
      description: 'Array of column keys to hide (works with both explicit and auto columns).',
    },
    {
      key: 'typeFilterKey',
      label: 'Type filter column',
      type: 'string',
      default: '',
      description: 'Column key to use as multi-select type filter bar (e.g. "type").',
    },
    {
      key: 'commonBadgeKeys',
      label: 'Common header badges',
      type: 'object',
      description:
        'Column keys whose single common value should be promoted to a header badge and hidden from table columns. Defaults to ["type"].',
    },
    {
      key: 'commonBadgeLabels',
      label: 'Common badge labels',
      type: 'object',
      description:
        'Optional display labels for common header badges, keyed by column name.',
    },
    {
      key: 'flattenRows',
      label: 'Flatten nested fields',
      type: 'boolean',
      default: false,
      description: 'Expand nested objects/arrays into flat columns.',
    },
    {
      key: 'rowIdKey',
      label: 'Row ID field',
      type: 'string',
      default: 'id',
    },
    {
      key: 'pageSize',
      label: 'Rows per page',
      type: 'number',
      default: 50,
    },
    {
      key: 'enableSearch',
      label: 'Show search input',
      type: 'boolean',
      default: true,
    },
    {
      key: 'enablePagination',
      label: 'Enable pagination',
      type: 'boolean',
      default: true,
    },
    {
      key: 'enableSorting',
      label: 'Enable column sorting',
      type: 'boolean',
      default: true,
    },
    {
      key: 'title',
      label: 'Table title',
      type: 'string',
      default: '',
    },
    {
      key: 'emptyText',
      label: 'Empty state text',
      type: 'string',
      default: 'No data',
    },
    {
      key: 'compact',
      label: 'Compact mode',
      type: 'boolean',
      default: false,
      description: 'Reduce row height and spacing for denser display.',
    },
    {
      key: 'columnSelector',
      label: 'Column selector',
      type: 'boolean',
      default: false,
      description:
        'Show a column visibility selector in the header. Meta/internal columns are grouped and hidden by default.',
    },
    {
      key: 'metaKeys',
      label: 'Metadata column keys',
      type: 'object',
      description:
        'Column keys to classify as metadata (hidden by default in selector). Auto-detected from key patterns when omitted.',
    },
    {
      key: 'paginationMode',
      label: 'Pagination mode',
      type: 'enum',
      default: 'client',
      options: ['client', 'server'],
      description:
        'client: all rows loaded upfront. server: fetches per page via onParamsChange({ offset, limit }).',
    },
    {
      key: 'searchHistoryKey',
      label: 'Search history storage key',
      type: 'string',
      default: '',
      description:
        'localStorage key for search history. Enables history dropdown when set.',
    },
    {
      key: 'enableRowSelection',
      label: 'Row selection',
      type: 'boolean',
      default: false,
      description: 'Enable the fixed first row-control column with checkbox selection and row numbers. Header select-all selects all filtered rows loaded in the table.',
    },
    {
      key: 'enableExpanding',
      label: 'Row expansion',
      type: 'boolean',
      default: false,
      description: 'Enable expandable rows showing JSON detail.',
    },
    {
      key: 'enableColumnResize',
      label: 'Column resize',
      type: 'boolean',
      default: false,
      description: 'Enable drag-to-resize column widths.',
    },
    {
      key: 'enableFieldSearch',
      label: 'Field-level search',
      type: 'boolean',
      default: false,
      description: 'Enable key:value and key~value search syntax for column-specific filtering.',
    },
    {
      key: 'enableContextMenu',
      label: 'Context menu',
      type: 'boolean',
      default: false,
      description: 'Fire rowRightClick action on right-click for external context menu rendering.',
    },
    {
      key: 'enableColoredTypes',
      label: 'Colored type badges',
      type: 'boolean',
      default: false,
      description: 'Assign distinct colors to type filter badges.',
    },
    {
      key: 'stickyFirstColumn',
      label: 'Sticky first column',
      type: 'boolean',
      default: false,
      description: 'Pin the first data column during horizontal scroll.',
    },
    {
      key: 'pageSizeOptions',
      label: 'Page size options',
      type: 'object',
      description: 'Array of page size options for the pagination selector. Default [25, 50, 100, 500].',
    },
    {
      key: 'urlStateKey',
      label: 'URL state key',
      type: 'string',
      default: '',
      description: 'Prefix for URL query param persistence. When set, search/sort/page state survives page refresh.',
    },
    {
      key: 'batchActions',
      label: 'Batch actions',
      type: 'object',
      description: 'Array of {id, label, icon?, variant?, disabled?, requiresSelection?} for buttons shown when rows are selected. Emits batchAction.',
    },
    {
      key: 'rowActions',
      label: 'Row actions',
      type: 'object',
      description: 'Array of {id, label, icon?, variant?, disabled?} for a per-row actions menu. Emits rowAction.',
    },
    {
      key: 'diffMode',
      label: 'Diff mode',
      type: 'boolean',
      default: false,
      description: 'Enable diff annotations: change_kind column, row coloring, and diff summary bar.',
    },
    {
      key: 'diffField',
      label: 'Diff field key',
      type: 'string',
      default: '_cstx_diff_change_kind',
      description: 'Row field containing the CstxChangeKind value for diff mode.',
    },
    {
      key: 'enableExport',
      label: 'Export button',
      type: 'boolean',
      default: false,
      description: 'Show export button in header. Fires export action via onAction.',
    },
    {
      key: 'exportFormats',
      label: 'Export formats',
      type: 'object',
      description: 'Array of export formats shown by the export button. Use ["csv"] for direct CSV download.',
    },
    {
      key: 'exportFilename',
      label: 'Export filename',
      type: 'string',
      default: 'export',
      description: 'Filename used by the built-in CSV download. Supports {rows}, {row}, {count}, and {selected} placeholders.',
    },
    {
      key: 'exportRequiresSelection',
      label: 'Export requires selection',
      type: 'boolean',
      default: false,
      description: 'Only show the export button after rows are selected. CSV export includes visible columns and selected rows.',
    },
  ],
  tags: ['table', 'data', 'list', 'cstx', 'filter', 'search', 'diff'],
};
