// @generated by cstx-codegen — DO NOT EDIT MANUALLY

export type RelationType = "resolve" | "open" | "has-subdomain" | "contain" | "hosts" | "uses" | "refers" | "secured_by" | "exploit" | "affect" | "invest" | "own" | "filed-for" | "vuln";

export const RELATION_TYPES = ["resolve", "open", "has-subdomain", "contain", "hosts", "uses", "refers", "secured_by", "exploit", "affect", "invest", "own", "filed-for", "vuln"] as const;

export interface SROBase {
  source_id: string;
  target_id: string;
  relation_type: RelationType;
  sources: string[];
}
