import type { ComponentType, SVGProps } from 'react'
import * as Lucide from 'lucide-react'

export type FileManagerIcon = ComponentType<SVGProps<SVGSVGElement> & { size?: number | string; strokeWidth?: number | string }>
const icon = (value: unknown) => value as FileManagerIcon

export const AlertTriangle = icon(Lucide.AlertTriangle)
export const ArrowDown = icon(Lucide.ArrowDown)
export const ArrowUp = icon(Lucide.ArrowUp)
export const ArrowUpDown = icon(Lucide.ArrowUpDown)
export const CheckCircle2 = icon(Lucide.CheckCircle2)
export const ChevronDown = icon(Lucide.ChevronDown)
export const ChevronRight = icon(Lucide.ChevronRight)
export const Copy = icon(Lucide.Copy)
export const Database = icon(Lucide.Database)
export const Download = icon(Lucide.Download)
export const Edit = icon(Lucide.Edit)
export const Eye = icon(Lucide.Eye)
export const File = icon(Lucide.File)
export const FileArchive = icon(Lucide.FileArchive)
export const FileAudio = icon(Lucide.FileAudio)
export const FileCode2 = icon(Lucide.FileCode2)
export const FileImage = icon(Lucide.FileImage)
export const FileJson = icon(Lucide.FileJson)
export const FilePlus = icon(Lucide.FilePlus)
export const FileSpreadsheet = icon(Lucide.FileSpreadsheet)
export const FileText = icon(Lucide.FileText)
export const FileVideo = icon(Lucide.FileVideo)
export const Folder = icon(Lucide.Folder)
export const FolderOpen = icon(Lucide.FolderOpen)
export const FolderPlus = icon(Lucide.FolderPlus)
export const Grid3X3 = icon(Lucide.Grid3X3)
export const HardDrive = icon(Lucide.HardDrive)
export const History = icon(Lucide.History)
export const Home = icon(Lucide.Home)
export const Info = icon(Lucide.Info)
export const List = icon(Lucide.List)
export const Loader2 = icon(Lucide.Loader2)
export const Menu = icon(Lucide.Menu)
export const RefreshCw = icon(Lucide.RefreshCw)
export const Search = icon(Lucide.Search)
export const Shield = icon(Lucide.Shield)
export const Trash2 = icon(Lucide.Trash2)
export const Upload = icon(Lucide.Upload)
export const Wifi = icon(Lucide.Wifi)
export const X = icon(Lucide.X)
export const XCircle = icon(Lucide.XCircle)
